"""add email verification code

Revision ID: 46202d7e17da
Revises: 4194c25f6da6
Create Date: 2025-11-29 18:10:06.719900

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '46202d7e17da'
down_revision = '4194c25f6da6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_verification_tokens', sa.Column('code', sa.String(), nullable=False))
    op.add_column('email_verification_tokens', sa.Column('attempts', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_verification_tokens', 'attempts')
    op.drop_column('email_verification_tokens', 'code')
    # ### end Alembic commands ###
