"""email verification code

Revision ID: 814777b460a3
Revises: 8f09708b9df6
Create Date: 2025-11-29 18:11:53.139959

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '814777b460a3'
down_revision = '8f09708b9df6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
